start_capture_hour: 14
end_capture_hour: 20
sleep_sec: 60
buffer_duration_sec: 30
frame_interval_sec: 2
DICT_VIDEO_URL:
  fontedatelha: "https://video-auth1.iol.pt/beachcam/fontedatelha/playlist.m3u8"
  # bclagoaalbufeira: "https://video-auth1.iol.pt/beachcam/bclagoaalbufeira/playlist.m3u8"
  # riviera: "https://video-auth1.iol.pt/beachcam/riviera/playlist.m3u8"